<?php
$_menuHtml    = $block->getHtml('level-top', 'submenu', 2);
?>

<div class="sn-mobile-menu-sort">
    <div class="sn-mobile-menu-sort__header">
        <div class="sn-mobile-menu-sort__header__title">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="17" viewBox="0 0 16 17" fill="none">
                <path d="M12.6665 5.37793C12.6665 6.4825 11.7711 7.37793 10.6665 7.37793C9.56193 7.37793 8.6665 6.4825 8.6665 5.37793M12.6665 5.37793C12.6665 4.27336 11.7711 3.37793 10.6665 3.37793C9.56193 3.37793 8.6665 4.27336 8.6665 5.37793M12.6665 5.37793L15.3332 5.37793M8.6665 5.37793H0.666504M7.33317 12.0446C7.33317 13.1492 6.43774 14.0446 5.33317 14.0446C4.2286 14.0446 3.33317 13.1492 3.33317 12.0446M7.33317 12.0446C7.33317 10.94 6.43774 10.0446 5.33317 10.0446C4.2286 10.0446 3.33317 10.94 3.33317 12.0446M7.33317 12.0446L15.3332 12.0446M3.33317 12.0446H0.666504" stroke="white" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            <span>Sort By</span>
        </div>
        <button class="sn-mobile-menu-sort__header__close close-sort">
            <span class="close-content">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="17" viewBox="0 0 16 17" fill="none">
                    <path d="M1 1.39355L15.1421 15.5357" stroke="white" stroke-linecap="round"/>
                    <path d="M1 15.6069L15.1421 1.4648" stroke="white" stroke-linecap="round"/>
                </svg>
                <span>Close</span>
            </span>
        </button>

    </div>
    <div class="sn-mobile-menu-sort__scroll">
        <div class="sn-mobile-menu-sort__menu">
            <ul class="sn-mobile-menu-sort__sub">
                <li class="level0 nav-1 category-item first parent align-container-top item-left">
                <a href="http://shark.local/index.php/vacuum-cleaners.html" class="level-top">
                    <span>Sort By</span>
                </a>
                </li>
                <li class="level0 nav-3 category-item first parent align-container-top item-left">
                <a href="http://shark.local/index.php/vacuum-cleaners.html" class="level-top">
                    <span>Price (Ascending)</span>
                </a>
                </li>
                <li class="level0 nav-3 category-item first parent align-container-top item-left">
              <a href="http://shark.local/index.php/vacuum-cleaners.html" class="level-top">
                <span>Price (Descending)</span>
              </a>
            </li>
            </ul>
        </div>
        <div class="sn-mobile-menu-sort__subnav bottom-filters">
            Applied Filters (0)
        </div>
    </div>
</div>

