<section class="our-range-action">
    <div class="page">
        <div class="owl-theme title">
            <h1><?= $block->escapeHtml(__('See it in action')) ?></h1>
            <h4><?= $block->escapeHtml(__('See how others are putting their Shark products to use and share your experiences with the ')) ?><strong>#sharkhome</strong> <?= $block->escapeHtml(__(' tag or tag us ')) ?><strong>@sharkhomeuk</strong></h4>
            <img src="<?= $block->getViewFileUrl('images/product-range/action.png') ?>" alt="See it in action"/>
        </div>
    </div>
</section>
