<section class="products-slider background-gray-200">
    <div class="container">
        <h3 class="products-slider__category-title" style="text-align:left !important;">Parts & Accessories</h3>
        <div class="slick-in">
        <div id="product-slick-slider" data-mage-init='
                {"slick": {
                "infinite": false,
                "dots": true,
                "slidesToShow": 4,
                "slidesToScroll": 1,
                "center": false,
                "responsive": [
                    {
                        "breakpoint": 391,
                        "settings": {
                            "slidesToShow": 1,
                            "navigation": false,
                            "arrows": false
                        }
                    },
                    {
                        "breakpoint": 769,
                        "settings": {
                            "slidesToShow": 2,
                            "arrows": true
                        }
                    },
                    {
                        "breakpoint": 1441,
                        "settings": {
                            "slidesToShow": 4
                        }
                    },
                    {
                        "breakpoint": 1920,
                        "settings": {
                            "slidesToShow": 5
                        }
                    }
                ]
            }}'>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">

                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool ')) ?></h4>
                                </div>
                                <div>
                                    <div class="quantity">
                                        <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Shark FlexStyle® 5-in-1 Air Styler & Hair Dryer with Storage Case - Black/Rose Gold " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool ')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">

                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool ')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool" class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool  " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool  ')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card product-card-responsive">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(28).png') ?>" alt="Duster Crevice Tool " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="accessories-title">
                                    <h4><?= $block->escapeHtml(__('Duster Crevice Tool ')) ?></h4>
                                </div>
                                <div class="quantity">
                                    <div class="box-tocart">
                                            <div class="fieldset">
                                                <div class="field qty">
                                                    <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity:') ?></span></label>
                                                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                                                        <!-- ko template: getTemplate() --><!-- /ko -->
                                                        <script type="text/x-magento-init">
                                                            {
                                                                "#custom-qty": {
                                                                    "Magento_Ui/js/core/app": {
                                                                        "components": {
                                                                            "qty-counter": {
                                                                                "component": "qty-counter",
                                                                                "config": {
                                                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        </script>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ46.51
                                    </span>
                                </div>

                                <a href="#" class="btn btn-black product-card__btn btn-sm btn-responsive">Add to cart</a>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>