<section class="offer-section">
    <div class="offer-section__image" style="background-image: url('<?php echo $block->getViewFileUrl('images/banners/offers.png'); ?>');"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-6">
                <div class="text-white offer-section__pre-title">There’s <span class="text-extra-bold">clean</span>, and then there’s <span class="text-extra-bold">Shark Clean</span></div>
                <h3 class="text-bold text-white offer-section__title">Save with Spring Clean Offers</h3>

                <a href="#" class="btn btn-white-outline btn-sm">Shop Now</a>

            </div>
        </div>
    </div>
</section>