<section class="products-slider background-gray-200">
    <div class="container">
        <h3 class="products-slider__title">Shop best sellers.</h3>
        <div class="slick-in">
            <div id="product-slick-slider" data-mage-init='
            {"slick": {
            "infinite": false,
            "dots": true,
            "slidesToShow": 5,
            "slidesToScroll": 1,
            "center": false,
            "responsive": [
                {
                    "breakpoint": 480,
                    "settings": {
                        "slidesToShow": 1,
                        "navigation": false,
                        "arrows": false
                    }
                },
                {
                    "breakpoint": 768,
                    "settings": {
                        "slidesToShow": 2,
                        "navigation": false,
                        "arrows": false
                    }
                },
                {
                    "breakpoint": 992,
                    "settings": {
                        "slidesToShow": 2
                    }
                },
                {
                    "breakpoint": 1200,
                    "settings": {
                        "slidesToShow": 3
                    }
                },
                {
                    "breakpoint": 1441,
                    "settings": {
                        "slidesToShow": 4
                    }
                },
                {
                    "breakpoint": 1681,
                    "settings": {
                        "slidesToShow": 5
                    }
                }
            ]
        }}'>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(22).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                <svg class="custom-star" style="margin-right: 3px; !important" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 12 12" fill="none">
                                    <path d="M5.44254 0.712134C5.64879 0.222257 6.35124 0.222258 6.55749 0.712135L7.77475 3.60347C7.86175 3.81 8.05835 3.9511 8.28402 3.96898L11.4436 4.21922C11.979 4.26162 12.196 4.92162 11.7882 5.26678L9.38089 7.30394C9.20896 7.44948 9.13382 7.67781 9.18636 7.89535L9.92182 10.9414C10.0464 11.4574 9.47816 11.8654 9.01982 11.5888L6.31474 9.95648C6.12152 9.83988 5.87851 9.83988 5.6853 9.95648L2.9802 11.5888C2.52187 11.8654 1.95358 11.4574 2.07819 10.9414L2.81366 7.89535C2.86619 7.67781 2.7911 7.44948 2.61916 7.30394L0.211838 5.26678C-0.196031 4.92162 0.0210408 4.26162 0.556376 4.21922L3.71602 3.96898C3.94171 3.9511 4.1383 3.81 4.22525 3.60347L5.44254 0.712134Z" fill="#FFBF0F"/>
                                    </svg>
                                    <svg class="custom-star" style="margin-right: 3px; !important" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 12 12" fill="none">
                                    <path d="M5.44254 0.712134C5.64879 0.222257 6.35124 0.222258 6.55749 0.712135L7.77475 3.60347C7.86175 3.81 8.05835 3.9511 8.28402 3.96898L11.4436 4.21922C11.979 4.26162 12.196 4.92162 11.7882 5.26678L9.38089 7.30394C9.20896 7.44948 9.13382 7.67781 9.18636 7.89535L9.92182 10.9414C10.0464 11.4574 9.47816 11.8654 9.01982 11.5888L6.31474 9.95648C6.12152 9.83988 5.87851 9.83988 5.6853 9.95648L2.9802 11.5888C2.52187 11.8654 1.95358 11.4574 2.07819 10.9414L2.81366 7.89535C2.86619 7.67781 2.7911 7.44948 2.61916 7.30394L0.211838 5.26678C-0.196031 4.92162 0.0210408 4.26162 0.556376 4.21922L3.71602 3.96898C3.94171 3.9511 4.1383 3.81 4.22525 3.60347L5.44254 0.712134Z" fill="#FFBF0F"/>
                                    </svg>
                                    <svg class="custom-star" style="margin-right: 3px; !important" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 12 12" fill="none">
                                    <path d="M5.44254 0.712134C5.64879 0.222257 6.35124 0.222258 6.55749 0.712135L7.77475 3.60347C7.86175 3.81 8.05835 3.9511 8.28402 3.96898L11.4436 4.21922C11.979 4.26162 12.196 4.92162 11.7882 5.26678L9.38089 7.30394C9.20896 7.44948 9.13382 7.67781 9.18636 7.89535L9.92182 10.9414C10.0464 11.4574 9.47816 11.8654 9.01982 11.5888L6.31474 9.95648C6.12152 9.83988 5.87851 9.83988 5.6853 9.95648L2.9802 11.5888C2.52187 11.8654 1.95358 11.4574 2.07819 10.9414L2.81366 7.89535C2.86619 7.67781 2.7911 7.44948 2.61916 7.30394L0.211838 5.26678C-0.196031 4.92162 0.0210408 4.26162 0.556376 4.21922L3.71602 3.96898C3.94171 3.9511 4.1383 3.81 4.22525 3.60347L5.44254 0.712134Z" fill="#FFBF0F"/>
                                    </svg>
                                    <svg class="custom-star" style="margin-right: 3px; !important" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 12 12" fill="none">
                                    <path d="M5.44254 0.712134C5.64879 0.222257 6.35124 0.222258 6.55749 0.712135L7.77475 3.60347C7.86175 3.81 8.05835 3.9511 8.28402 3.96898L11.4436 4.21922C11.979 4.26162 12.196 4.92162 11.7882 5.26678L9.38089 7.30394C9.20896 7.44948 9.13382 7.67781 9.18636 7.89535L9.92182 10.9414C10.0464 11.4574 9.47816 11.8654 9.01982 11.5888L6.31474 9.95648C6.12152 9.83988 5.87851 9.83988 5.6853 9.95648L2.9802 11.5888C2.52187 11.8654 1.95358 11.4574 2.07819 10.9414L2.81366 7.89535C2.86619 7.67781 2.7911 7.44948 2.61916 7.30394L0.211838 5.26678C-0.196031 4.92162 0.0210408 4.26162 0.556376 4.21922L3.71602 3.96898C3.94171 3.9511 4.1383 3.81 4.22525 3.60347L5.44254 0.712134Z" fill="#FFBF0F"/>
                                    </svg> 
                                    <svg class="custom-star" style="margin-right: 3px; !important" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 12 12" fill="none">
                                    <path d="M5.44254 0.712134C5.64879 0.222257 6.35124 0.222258 6.55749 0.712135L7.77475 3.60347C7.86175 3.81 8.05835 3.9511 8.28402 3.96898L11.4436 4.21922C11.979 4.26162 12.196 4.92162 11.7882 5.26678L9.38089 7.30394C9.20896 7.44948 9.13382 7.67781 9.18636 7.89535L9.92182 10.9414C10.0464 11.4574 9.47816 11.8654 9.01982 11.5888L6.31474 9.95648C6.12152 9.83988 5.87851 9.83988 5.6853 9.95648L2.9802 11.5888C2.52187 11.8654 1.95358 11.4574 2.07819 10.9414L2.81366 7.89535C2.86619 7.67781 2.7911 7.44948 2.61916 7.30394L0.211838 5.26678C-0.196031 4.92162 0.0210408 4.26162 0.556376 4.21922L3.71602 3.96898C3.94171 3.9511 4.1383 3.81 4.22525 3.60347L5.44254 0.712134Z" fill="#FFBF0F"/>
                                    </svg>     
                                <span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <div class="product-card__exclusive">
                                <img src="<?= $block->getViewFileUrl('images/exclusive.svg') ?>" alt="Web Exclusive Icon" />
                                <span>Web exclusive</span>
                            </div>
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(24).png') ?>" alt="Shark FlexStyle® 5-in-1 Air Styler & Hair Dryer with Storage Case - Black/Rose Gold " class="product-card__image-exclusive img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">

                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(22).png') ?>" alt="Shark CarpetXpert Deep Clean Pro Formula for Shark Upright & Portable Carpet cleaners " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(24).png') ?>" alt="Shark Stratos Anti Hair Wrap Plus Pet Pro Cordless Vacuum (Double Battery)" class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Stratos Anti Hair Wrap Plus Pet Pro Cordless Vacuum (Double Battery)')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(25).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner  " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner  ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(24).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Cordless Vacuum Stratos')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card" onclick="location.href='/your-product-url'">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(22).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>