<section class="two-product-cards">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="two-product-card">
                    <div class="two-product-card__image" style="background-image: url('<?php echo $block->getViewFileUrl('images/cards/card_4.jpg'); ?>');"></div>
                    <div class="two-product-card__body">
                        <h5 class="two-product-card__title text-white text-bold">Shark Matrix™</h5>
                        <h6 class="two-product-card__subtitle text-white text-md text-regular">Clean air. Clean hands. Clean home.</h6>
                        <a href="#" class="btn btn-white two-product-card__button btn-xs">Shop Robot Vacuums</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="two-product-card">
                    <div class="two-product-card__image" style="background-image: url('<?php echo $block->getViewFileUrl('images/cards/card_5.jpg'); ?>');"></div>
                    <div class="two-product-card__body">
                        <h5 class="two-product-card__title text-white text-bold">Shark® FlexBreeze™</h5>
                        <h6 class="two-product-card__subtitle text-white text-md text-regular">Indoor to outdoor. Cordless to corded.</h6>
                        <a href="#" class="btn btn-white two-product-card__button btn-xs">Shop Fans</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>