<section class="upsell-cards">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-sm-12">
                <div class="upsell-card">
                    <div class="upsell-card__icon truck"></div>
                    <div>
                        <h5 class="text-bold text-md">Free Next Day Delivery</h5>
                        <p class="text-sm">7 Days a Week* Terms Apply</p>
                    </div>
                    <a class="upsell-card__arrow" href="#"></a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="upsell-card">
                    <div class="upsell-card__icon sheild"></div>
                    <div>
                        <h5 class="text-bold text-md">Up to 5-Year Guarantee*</h5>
                        <p class="text-sm">Confidence in our design and quality</p>
                    </div>
                    <a class="upsell-card__arrow" href="#"></a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="upsell-card">
                    <div class="upsell-card__icon return"></div>
                    <div>
                        <h5 class="text-bold text-md">30 Days Returns</h5>
                        <p class="text-sm">Free returns on main units</p>
                    </div>
                    <a class="upsell-card__arrow" href="#"></a>
                </div>
            </div>
            <div class="col-lg-3 col-sm-12">
                <div class="upsell-card mb-0">
                    <div class="upsell-card__icon klarna"></div>
                    <div>
                        <h5 class="text-bold text-md">Pay-in-3</h5>
                        <p class="text-sm">Shop now, pay later with Klarna</p>
                    </div>
                    <a class="upsell-card__arrow" href="#"></a>
                </div>
            </div>
        </div>
    </div>
    <div class="upsell-modal">
        <div class="upsell-modal__container">
            <div class="upsell-modal__close">
                <svg xmlns="http://www.w3.org/2000/svg" width="14" height="15" viewBox="0 0 14 15" fill="none">
                    <path d="M1.04883 1.54883L12.8915 13.3915M1.04883 13.4512L12.8915 1.60849" stroke="white" stroke-width="1.2561" stroke-linecap="round" />
                </svg>
            </div>
            <div class="upsell-modal__header">
                <div class="upsell-modal__icon upsell-card__icon shield">
                </div>
                <div>
                    <h3 class="upsell-modal__title">Up to 5-Year Guarantee*</h3>
                    <p class="upsell-modal__subtitle">Confidence in our design and quality</p>
                </div>
            </div>
            <div class="upsell-modal__body">

                <p class="upsell-modal__p1">We're sure you'll love your new Shark!</p>
                <p class="upsell-modal__p2">Enjoy a free guarantee of up to 5 years* for total peace of mind.</p>
                <p class="upsell-modal__p3">Here's how it works</p>

                <div class="upsell-modal__list">
                    <div class="upsell-modal__list-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                            <path d="M13 6.45143V7.00343C12.9993 8.29729 12.5803 9.55624 11.8056 10.5925C11.0309 11.6288 9.94197 12.3869 8.70121 12.7538C7.46046 13.1206 6.13435 13.0766 4.92068 12.6282C3.70701 12.1798 2.67079 11.3511 1.96658 10.2657C1.26236 9.18025 0.927875 7.89627 1.01301 6.60522C1.09814 5.31417 1.59832 4.08523 2.43897 3.10168C3.27961 2.11813 4.41567 1.43266 5.67771 1.14752C6.93975 0.86238 8.26016 0.992836 9.442 1.51943M13 2.20343L7 8.20943L5.2 6.40943" stroke="black" stroke-width="1.125" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                        <p>When you buy directly from Shark, your warranty is automatically registered, so there's nothing for you to do.</p>
                    </div>
                    <div class="upsell-modal__list-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                            <path d="M13 6.45143V7.00343C12.9993 8.29729 12.5803 9.55624 11.8056 10.5925C11.0309 11.6288 9.94197 12.3869 8.70121 12.7538C7.46046 13.1206 6.13435 13.0766 4.92068 12.6282C3.70701 12.1798 2.67079 11.3511 1.96658 10.2657C1.26236 9.18025 0.927875 7.89627 1.01301 6.60522C1.09814 5.31417 1.59832 4.08523 2.43897 3.10168C3.27961 2.11813 4.41567 1.43266 5.67771 1.14752C6.93975 0.86238 8.26016 0.992836 9.442 1.51943M13 2.20343L7 8.20943L5.2 6.40943" stroke="black" stroke-width="1.125" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                        <p>When you buy directly from Shark, your warranty is automatically registered, so there's nothing for you to do.</p>
                    </div>
                    <div class="upsell-modal__list-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                            <path d="M13 6.45143V7.00343C12.9993 8.29729 12.5803 9.55624 11.8056 10.5925C11.0309 11.6288 9.94197 12.3869 8.70121 12.7538C7.46046 13.1206 6.13435 13.0766 4.92068 12.6282C3.70701 12.1798 2.67079 11.3511 1.96658 10.2657C1.26236 9.18025 0.927875 7.89627 1.01301 6.60522C1.09814 5.31417 1.59832 4.08523 2.43897 3.10168C3.27961 2.11813 4.41567 1.43266 5.67771 1.14752C6.93975 0.86238 8.26016 0.992836 9.442 1.51943M13 2.20343L7 8.20943L5.2 6.40943" stroke="black" stroke-width="1.125" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                        <p>If you purchase from another retailer, you'll need to <a href="">register your product</a> within 28 days of purchase.</p>
                    </div>
                    <div class="upsell-modal__list-item">
                        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 14 14" fill="none">
                            <path d="M13 6.45143V7.00343C12.9993 8.29729 12.5803 9.55624 11.8056 10.5925C11.0309 11.6288 9.94197 12.3869 8.70121 12.7538C7.46046 13.1206 6.13435 13.0766 4.92068 12.6282C3.70701 12.1798 2.67079 11.3511 1.96658 10.2657C1.26236 9.18025 0.927875 7.89627 1.01301 6.60522C1.09814 5.31417 1.59832 4.08523 2.43897 3.10168C3.27961 2.11813 4.41567 1.43266 5.67771 1.14752C6.93975 0.86238 8.26016 0.992836 9.442 1.51943M13 2.20343L7 8.20943L5.2 6.40943" stroke="black" stroke-width="1.125" stroke-linecap="round" stroke-linejoin="round" />
                        </svg>
                        <p>Need help with your product? Visit our <a href="#">Customer Support</a> section</p>
                    </div>
                </div>

                <p class="upsell-modal__terms">*Upon registration with Shark. Duration may vary, see products for details.</p>

                <a href="#" class="btn">More Info</a>
            </div>
        </div>
    </div>
</section>