version: "3"

networks:
  magento:

services:
  web:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: web_${SITE}
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=${WEB_ALIAS_DOMAIN}
      - WEB_DOCUMENT_ROOT=${WEB_DOCUMENT_ROOT}
      - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE}
      - PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS}
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE}
    volumes:
      - ./backend:/app:cached
    ports:
      - ${FRONTEND_PORT}:80
      - ${FRONTEND_SSL_PORT}:443
      - ${FRONTEND_SSH_PORT}:22
    networks:
      magento:
    links:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_${SITE}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SERVICE_TAGS=${SERVICE_TAGS}
      - SERVICE_NAME=${SERVICE_NAME}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      magento:

  redis:
    image: redis:latest
    container_name: redis_${SITE}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis:/data
    networks:
      magento:

  redis-session:
    image: redis
    container_name: redis_session_${SITE}
    ports:
      - ${REDIS_SESSION_PORT}:6379
    networks:
      magento:

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_${SITE}
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_SSL_PORT}:8025
    networks:
      magento:

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    container_name: elasticsearch_${SITE}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node-1
      - cluster.initial_master_nodes=node-1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    networks:
      magento:

  composer:
    profiles: ["commands"]
    build:
      context: ./composer
      dockerfile: Dockerfile
    container_name: composer_${SITE}
    volumes:
      - ./backend:/app
    working_dir: /app
    user: magento
    #entrypoint: ["composer", "install", "--ignore-platform-reqs"]
    networks:
      magento:

  adminer:
    image: adminer
    container_name: adminer_${SITE}
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      magento:

volumes:
  mysql:
    external: false
  redis:
    external: false
