<nav class="header__inner__controls__nav">
    <a href="#" class="header__inner__controls__nav__icon header__inner__controls__nav__icon--search"></a>
    <a href="#" class="header__inner__controls__nav__icon header__inner__controls__nav__icon--account"></a>
    <a href="#" class="header__inner__controls__nav__icon header__inner__controls__nav__icon--basket"></a>
    <a href="#" class="header__inner__controls__nav__icon header__inner__controls__nav__icon--menu"></a>
</nav>