<div class="header__promo">
    End of Winter savings - <a>Up to 33% off*</a>
</div>

<script>
require(['jquery'], function($) {
    $(document).ready(function() {
        $('.minicart-wrapper').hover(
            function() { // Mouse enter
                if (!$('.minicart-wrapper .block-minicart').is(':visible')) {
                    $('.action.showcart').trigger('click');
                }
            }, 
            function() { // Mouse leave
                if ($('.minicart-wrapper .block-minicart').is(':visible')) {
                    $('.action.showcart').trigger('click');
                }
            }
        );
    });
});
</script>

