<div class="sn-user-header">
    <div class="sn-logo-selector">
        The SharkNinja family: <img src="<?= $block->getViewFileUrl('images/logo.svg') ?>" /> | <img src="<?= $block->getViewFileUrl('images/ninja_logo.svg') ?>" />
    </div>
    <div class="sn-user-links">
        <a href="">Register my guarantee</a>
        <a href="">Customer care</a>
        <a href="">Sign In</a>
        <a href="">Register</a>
    </div>
</div>