<div class="features-tab-button products-tabs__button active">
    <div class="container">
        <a href="#features-tab">Features</a>
    </div>
</div>
<div class="features-tab products-tabs__pannel active">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-lg-6 order-lg-1 order-sm-2 order-xs-2 features-container">
                <?php // the design required a duplicte title in this block 
                ?>
                <h3 class="hideDuplicateTitleBelowTablet">Product Features</h3>
                <div class="accordions">
                    <div class="accordions__section-container">
                        <div class="accordions__section active">
                            <a href="#accordion-1">4 deep-cleaning technologies</a>
                            <div class="accordions__section__content">
                                <p>Four Detect Pro technologies track down every hidden mess in your home and optimise performance. DirtDetect automatically boosts suction for deep cleaning on carpets. EdgeDetect doubles suction for more powerful edge and corner cleaning. FloorDetect auto-detects floor type and optimises performance. LightDetect illuminates low-light areas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="accordions__section-container">
                        <div class="accordions__section">
                            <a href="#accordion-2">Deep clean all floors</a>
                            <div class="accordions__section__content">
                                <p>Four Detect Pro technologies track down every hidden mess in your home and optimise performance. DirtDetect automatically boosts suction for deep cleaning on carpets. EdgeDetect doubles suction for more powerful edge and corner cleaning. FloorDetect auto-detects floor type and optimises performance. LightDetect illuminates low-light areas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="accordions__section-container">
                        <div class="accordions__section">
                            <a href="#accordion-3">Up to 60 minutes of run-time**</a>
                            <div class="accordions__section__content">
                                <p>Four Detect Pro technologies track down every hidden mess in your home and optimise performance. DirtDetect automatically boosts suction for deep cleaning on carpets. EdgeDetect doubles suction for more powerful edge and corner cleaning. FloorDetect auto-detects floor type and optimises performance. LightDetect illuminates low-light areas.</p>
                            </div>
                        </div>
                    </div>
                    <div class="accordions__section-container">
                        <div class="accordions__section">
                            <a href="#accordion-4">Transforms into a handvac</a>
                            <div class="accordions__section__content">
                                <p>Four Detect Pro technologies track down every hidden mess in your home and optimise performance. DirtDetect automatically boosts suction for deep cleaning on carpets. EdgeDetect doubles suction for more powerful edge and corner cleaning. FloorDetect auto-detects floor type and optimises performance. LightDetect illuminates low-light areas.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-12 col-lg-6 order-lg-2 order-sm-1 order-xs-1">
                <h3 class="hideDuplicateTitleAboveTablet">Product Features</h3>
                <img src="<?= $block->getViewFileUrl('images/product-landing/product-features.jpeg') ?>" alt="bazar" style="margin-top:20px; width:100%; height:auto;" />
            </div>
        </div>
    </div>
</div>