<div class="container">
    <div class="products-tabs">
        <div class="products-tabs__nav">
            <a href="#features-tab" class="active">Features</a>
            <a href="#product-details-tab">Product Details</a>
            <a href="#product-spec-tab">Product Specification</a>
            <a href="#whats-included-tab">What's Included</a>
            <a href="#faqs-tab">FAQs</a>
            <a href="#product-support-tab">Product Support</a>
        </div>
    </div>
</div>