<div class="product-details-tab-button products-tabs__button">
    <div class="container">
        <a href="#product-details-tab">Product Details</a>
    </div>

</div>

<div class="product-details-tab products-tabs__pannel">
    <div class="container product-tab">
        <h2><?= $block->escapeHtml(__('Introducing Detect Pro')) ?></h2>
        <p class="text-lg"><?= $block->escapeHtml(__('Shark\'s most intelligent vacuum cleaner range. This ultra-lightweight, deep-cleaning cordless intelligently adapts to every mess.')) ?></p>

        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Up to 50% better dirt pick-up')) ?>
                <div class="info-svg"></div>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('4 deep-cleaning technologies detect and react to their surroundings, tracking down every hidden mess in your home.')) ?></p>
                <ul class="grey-cards">
                    <li><strong><?= $block->escapeHtml(__('DirtDetect')) ?></strong><br><?= $block->escapeHtml(__('Detects dirt you can\'t see and automatically boosts suction power for deep cleaning on carpets.')) ?></li>
                    <li><strong><?= $block->escapeHtml(__('EdgeDetect')) ?></strong><br><?= $block->escapeHtml(__('Senses edges and doubles suction for more powerful edge and corner cleaning.')) ?></li>
                    <li><strong><?= $block->escapeHtml(__('FloorDetect')) ?></strong><br><?= $block->escapeHtml(__('Auto-detects floor type and optimises performance, increasing the brush-roll speed up to 2x for deep cleaning on carpet.')) ?></li>
                    <li><strong><?= $block->escapeHtml(__('LightDetect')) ?></strong><br><?= $block->escapeHtml(__('Responds to low-light areas, automatically illuminating hidden dust and debris.')) ?></li>
                </ul>

                <p class="text-lg"><?= $block->escapeHtml(__('Enjoy up to')) ?> <strong title="" data-mage-init='{"tooltip":{"trigger":"hover"}}' style="text-decoration: underline;"><?= $block->escapeHtml(__('60 minutes of run-time')) ?></strong> <?= $block->escapeHtml(__('and charge the removable battery anywhere around your home.')) ?></p>
                <p class="text-lg"><strong><?= $block->escapeHtml(__('Anti-Allergen Complete Seal')) ?></strong> <?= $block->escapeHtml(__('captures and traps')) ?> <strong><?= $block->escapeHtml(__('99.9% of dust, allergens and irritants')) ?></strong> <?= $block->escapeHtml(__('inside the vacuum, not releasing them back into your home. Perfect for homes with')) ?><strong><?= $block->escapeHtml(__('pets or allergy sufferers')) ?></strong>.</p>

            </div>
        </div>



        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Deep clean carpets and hard floors:')) ?>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('The')) ?> <strong><?= $block->escapeHtml(__('QuadClean multi-surface brush-roll')) ?></strong> <?= $block->escapeHtml(__('deep cleans all floor types – with no swapping. This unique design features a raised front edge to pull in large particles, carpet fins to lift embedded dirt and hair, agitation ribs to loosen fine dirt, and soft microfibre to capture fine dust.')) ?></p>
                <p class="text-lg"><strong><?= $block->escapeHtml(__('Anti Hair Wrap Technology')) ?></strong><?= $block->escapeHtml(__('removes hair from the brush-roll as you clean, helping to keep it tangle-free.')) ?></p>

            </div>
        </div>

        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Powerful performance, 25% lighter:')) ?>
                <div class="info-svg"></div>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('A compact turbo-drive motor packs')) ?><strong><?= $block->escapeHtml(__('powerful cleaning performance')) ?></strong><?= $block->escapeHtml(__('into this ultra-lightweight cordless vacuum. An')) ?> <strong><?= $block->escapeHtml(__('LED display')) ?></strong> <?= $block->escapeHtml(__('screen shows real-time battery status, dirt detection and cleaning mode read-outs')) ?>.</p>
            </div>
        </div>
        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Whole-home cleaning:')) ?>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('Not just for floors, detach the handheld vacuum to easily clean stairs, soft furnishings, inside the car and hard-to-reach places with the')) ?><strong><?= $block->escapeHtml(__('lightweight handvac')) ?></strong> <?= $block->escapeHtml(__('and')) ?><strong><?= $block->escapeHtml(__('Duster-Crevice Tool')) ?></strong> <?= $block->escapeHtml(__('attachment')) ?>.</p>
            </div>
        </div>
        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Easy freestanding storage:')) ?>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('Simply detach the handvac and clip it at the base of the wand for')) ?> <strong><?= $block->escapeHtml(__('freestanding storage')) ?></strong>,<?= $block->escapeHtml(__('anywhere in your home')) ?>.</p>
            </div>
        </div>
        <div class="row border-top">
            <div class="col-md-5 tbordgreytitle">
                <?= $block->escapeHtml(__('Shark guarantee:')) ?>
            </div>
            <div class="col-md-7 tbordgrey">
                <p class="text-lg"><?= $block->escapeHtml(__('Shark offers a')) ?> <strong><?= $block->escapeHtml(__('5-year guarantee (2 years for batteries)')) ?></strong><?= $block->escapeHtml(__('so you can clean with confidence')) ?>.</p>
            </div>
        </div>
    </div>
</div>