<div class="whats-included-tab-button products-tabs__button">
    <div class="container">
        <a href="#whats-included-tab">What's Included</a>
    </div>
</div>
<div class="background-gray-200 whats-included-tab products-tabs__pannel">
    <div class="container product-included">
        <h2><?= $block->escapeHtml(__('In the box')) ?></h2>
        <div class="row">
            <div class="col-3">
                <div class="included-card">
                    <img src="<?= $block->getViewFileUrl('images/productdisplay/main-unit-image.png') ?>" alt="Main Unit" class="img-fluid" />
                    <p><?= $block->escapeHtml(__('Main Unit')) ?></p>
                </div>
            </div>
            <div class="col-3">
                <div class="included-card">
                    <img src="<?= $block->getViewFileUrl('images/productdisplay/duster-crevice-tool-image.png') ?>" alt="Duster Crevice Tool" class="img-fluid" />
                    <p><?= $block->escapeHtml(__('Duster Crevice Tool')) ?></p>
                </div>
            </div>
            <div class="col-3">
                <div class="included-card">
                    <img src="<?= $block->getViewFileUrl('images/productdisplay/charger-image.png') ?>" alt="Charger" class="img-fluid" />
                    <p><?= $block->escapeHtml(__('Charger')) ?></p>
                </div>
            </div>
            <div class="col-3">
                <div class="included-card">
                    <img src="<?= $block->getViewFileUrl('images/productdisplay/base-clip-image.png') ?>" alt="Base Clip" class="img-fluid" />
                    <p><?= $block->escapeHtml(__('Base Clip')) ?></p>
                </div>
            </div>
        </div>
    </div>


</div>