
<div class="container-cookie-notice">
    <div class="row">
    <div class="cookie-heading">
                    <h1 class="title"><?= $block->escapeHtml(__('Cookie Notice')) ?></h1>
                    <h6 class="subtitle"><?= $block->escapeHtml(__('Updated: January 14, 2021')) ?></h6>
                </div>
        <div class="col-md-8">
                <div class="cookie-content">
                    <p><?= $block->escapeHtml(__('We use cookies to personalise your consumer experience through content, advertisements, social media features, and analysis of our website traffic data. We also share information on your use of our site with our social media, advertising, and analytics partners. You can read more about any of our purposes or the vendors that we use by clicking on ‘Cookie Settings.’ The preference centre is accessible at any time through the ‘Cookie Settings’')) ?></p>
                    <a href="#" class="btn btn-white"><?= $block->escapeHtml(__('Cookies Settings')) ?></a>
                    <p><?= $block->escapeHtml(__('When you visit any website, it may store or retrieve information using your browser, mostly in the form of cookies. This information might be personal information about you, your preferences or your device and is mostly used to make the site work as you expect it to. The information does not usually directly identify you, but it can give you a more personalised web experience. Because we respect your right to privacy, you can choose not to allow some types of cookies.')) ?></p>
                    <p><?= $block->escapeHtml(__('You have the option to accept or decline the use of cookies using the on/off settings of the preference centre, by clicking')) ?></p>
                    <a href="#" class="btn btn-white"><?= $block->escapeHtml(__('Cookies Settings')) ?></a>
                </div>
                <div class="cookie-accordian">
                    <div id="accordian" data-mage-init='{"accordion":{ "active": [0], "collapsible": true, "openedState": "active", "multipleCollapsible": true }}'>
                        <div class="panel panel-default" data-role="collapsible">
                            <div class="panel-heading" data-role="trigger">
                                <h4 class="panel-title"><?= $block->escapeHtml(__('What is a cookie?')) ?></h4>
                                <button class="shark-up toggle-shark"></button>
                            </div>
                            <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p><?= $block->escapeHtml(__('A cookie is a small piece of data...')) ?></p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                            <div class="panel-heading" data-role="trigger">
                                <h4 class="panel-title"><?= $block->escapeHtml(__('Why do we use a cookie?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                            <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">    
                            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('What types of cookies do we use?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('First Party Cookies')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                                     <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('Third Party Cookies')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                                     <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('What categories of cookie are on our website?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Strictly necessary cookies')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Performance & analytics cookies')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Functional cookies')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Profiling and targeting cookies')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Do we share data collected through cookies?')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('TaggStar')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Google Analytics')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Google Ads')) ?></h4>
            <button class="shark-down toggle-shark"></button>
            </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Google Enhanced Conversions')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Facebook (Meta)')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('How to customise your cookie settings')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('How to contact us')) ?></h4>
            <button class="shark-down toggle-shark"></button>
       </div>
       <div data-role ="content" class="panel-collapse collapse in">
                            <div class="panel-body">
           <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
</div>
        <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('More information')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
</div>
                </div>
            </div>
        </div>

        <!-- Side panel for 'card-difficulty', occupying 30% of the width on the right -->
        <div class="col-md-4">
            <div class="card-difficulty">
                <div class="card-title">
                    <img src="<?= $block->getViewFileUrl('images/icons/question-icon.png') ?>" alt="package icon" class="img-fluid mb-2" style="max-width: 50px;">
                    <h6><?= $block->escapeHtml(__('Having difficulties?')) ?></h6>
                </div>
                    <p class="card-body"><?= $block->escapeHtml(__('If you have any problems or need help, please contact our Customer Service.')) ?></p>
                    <button class="btn-primary" href="<?= $block->getUrl('contact') ?>"><?= $block->escapeHtml(__('Go to support centre')) ?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var toggleButtons = document.querySelectorAll('.toggle-shark');
    toggleButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            if (this.classList.contains('shark-up')) {
                this.classList.remove('shark-up');
                this.classList.add('shark-down');
            } else {
                this.classList.remove('shark-down');
                this.classList.add('shark-up');
            }
        });
    });
});
</script>
