<div class="feature-list showOnMobile">
   <ul>
      <li>The <strong>ultra-lightweight, deep-cleaning</strong> cordless vacuum</li>
      <li>4 technologies for up to 50% <strong>better dirt pick-up</strong> <a href="#" class="feature-list__info"></a></li>
      <li>Detects and reacts to debris, floor types, edges & light</li>
      <li>Powerful performance, <strong>25% lighter</strong> <a href="#" class="feature-list__info"></a></li>
      <li>Deep cleans carpets & hard floors with QuadClean floorhead with <strong>Anti Hair Wrap</strong></li>
   </ul>
</div>

<section class="delivery-badge-container">
   <div class="delivery-badge">
      <span></span>
      <?= $block->escapeHtml(__('Pay with cash or card on delivery')) ?>
   </div>
</section>