<div class="fixed-banner">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-8 col-lg-8 col-xl-6 left">
                <h4>Shark Detect Pro Cordless Vacuum Cleaner</h4>
                <span>1635.85د.إ</span>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 col-xl-6 right">
                <span>1635.85د.إ</span>
                <a href="#" class="btn btn-orange">Add To Cart</a>
            </div>
        </div>
    </div>
</div>