<div class="payment">
    <?php

    //this element was originally a screenshot in the figma file (lazy tall)
    //it will be difficult for tall to QA this part without them actually designing it properly. 
    //Colours and spacing have been matched by "eyeballing it"

    // https://app.clickup.com/t/8694mcrbu 
    // another update above. Tall are relying on an external plugin to do this visual work. 

    ?>
    <!-- <div class="container product-protection">
        <div class="product-protection__cards">
            <div class="row">
                <div class="col-12">
                    <h5 class="protection-title"><?= $block->escapeHtml(__('Add product protection')) ?></h5>
                    <div class="row">
                        <div class="col-md-4 card">
                            <div class="card-body">
                                <h6 class="card-title"><?= $block->escapeHtml(__('1-Year')) ?> </h6>
                                <p class="card-text"><?= $block->escapeHtml(__('US$ 19.99')) ?></p>
                            </div>
                        </div>
                        <div class="col-md-4 card">
                            <div class="card-body">
                                <h6 class="card-title"><?= $block->escapeHtml(__('2-Year')) ?> </h6>
                                <p class="card-text"><?= $block->escapeHtml(__('US$ 29.99')) ?></p>
                            </div>
                        </div>
                        <div class="col-md-4 card">
                            <div class="card-body">
                                <h6 class="card-title"><?= $block->escapeHtml(__('3-Year')) ?> </h6>
                                <p class="card-text"><?= $block->escapeHtml(__('US$ 39.99')) ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <a href="#" class="text-black"><?= $block->escapeHtml(__('What\'s Covered?')) ?> </a>
        <p class="right text-black"><?= $block->escapeHtml(__('Powered by')) ?> <a href="https://xcover.com"><?= $block->escapeHtml(__('XCOVER.COM')) ?></a></p>
    </div>
</div>
</div> -->

    <img src="<?= $block->getViewFileUrl('images/placeholders/xcover.png') ?>" alt="xcover" style="margin-top:20px; width:100%; height:auto;" />
</div>