<div class="payment">

    <p><?= $block->escapeHtml(__('As low as £16.58/month with')) ?><img src="<?= $block->getViewFileUrl('images/icons/paypal-credit-icon.png') ?>" alt="Delivery Van Icon" class="img-fluid" /> <a class="tooltip-content" href="">Learn More</a></p>
    <p><?= $block->escapeHtml(__('As low as £66.33/month with')) ?> <img src="<?= $block->getViewFileUrl('images/icons/klarna-icon.png') ?>" alt="Delivery Van Icon" class="img-fluid" /> <a class="tooltip-content" href="">Learn More</a></p>
    <p class="text-xs text-gray-500">18+, T&C apply, Credit subject to status.</p>

</div>
<?php
// brain dead designer has flipped the content so the buy now button appears here
?>
<div class="feature-list hideOnMobile">
    <ul>
        <li>The <strong>ultra-lightweight, deep-cleaning</strong> cordless vacuum</li>
        <li>4 technologies for up to 50% <strong>better dirt pick-up</strong>
            <a href="#" class="feature-list__info">
                <div class="tooltip">
                    <svg xmlns="http://www.w3.org/2000/svg" width="9" height="11" viewBox="0 0 9 11" fill="none">
                        <path d="M0.5 6.36603C-0.166667 5.98113 -0.166667 5.01888 0.5 4.63397L7.25 0.736861C7.91667 0.351961 8.75 0.833087 8.75 1.60289L8.75 9.39711C8.75 10.1669 7.91667 10.648 7.25 10.2631L0.5 6.36603Z" fill="#295BFF" />
                    </svg>
                    Vs Shark IZ400
                </div>
            </a>

        </li>
        <li>Detects and reacts to debris, floor types, edges & light</li>
        <li>Powerful performance, <strong>25% lighter</strong>
            <a href="#" class="feature-list__info">
                <div class="tooltip">
                    <svg xmlns="http://www.w3.org/2000/svg" width="9" height="11" viewBox="0 0 9 11" fill="none">
                        <path d="M0.5 6.36603C-0.166667 5.98113 -0.166667 5.01888 0.5 4.63397L7.25 0.736861C7.91667 0.351961 8.75 0.833087 8.75 1.60289L8.75 9.39711C8.75 10.1669 7.91667 10.648 7.25 10.2631L0.5 6.36603Z" fill="#295BFF" />
                    </svg>
                    Vs Shark IZ400
                </div>
            </a>
        </li>
        <li>Deep cleans carpets & hard floors with QuadClean floorhead with <strong>Anti Hair Wrap</strong></li>
    </ul>
</div>