<div class="container-privacy-notice">
    <div class="row">
        <div class="privacy-heading">
                    <h1 class="title"><?= $block->escapeHtml(__('Privacy Notice')) ?></h1>
                    <h6 class="subtitle"><?= $block->escapeHtml(__('Updated: January 14, 2021')) ?></h6>
        </div>
        <div class="col-md-8">
            <div class="privacy-content">
                    <p><?= $block->escapeHtml(__('These terms of use govern your use of our website; by using our website, you accept these terms of use in full. If you disagree with these terms of use or any part of these terms of use, you must not use our website.')) ?></p>
                    <p><?= $block->escapeHtml(__('If you register with our website we will ask you to expressly agree to these terms of use.')) ?></p>
                <ul>
                    <li><?= $block->escapeHtml(__('access or use any of our websites, including product order transactions, downloading material including product manuals and FAQs,')) ?></li>
                    <li><?= $block->escapeHtml(__('use any of our products, services or applications in any manner,')) ?></li>
                    <li><?= $block->escapeHtml(__('participate in a research survey or testing and register your products with us.')) ?></li>
                </ul>
            <p style="font-weight:bold;"><?= $block->escapeHtml(__('If you want to read about our Robotics Connected Devices Privacy Notice, please')) ?>
            <a href="<?= $block->getUrl('contact') ?>"><?= $block->escapeHtml(__('click here')) ?></a></p>
            </div>
                <div class="privacy-accordian">
                    <div id="accordian" data-mage-init='{"accordion":{ "active": [0], "collapsible": true, "openedState": "active", "multipleCollapsible": true }}'>
                        <div class="panel panel-default" data-role="collapsible">
                            <div class="panel-heading" data-role="trigger">
                                <h4 class="panel-title"><?= $block->escapeHtml(__('Who is responsible for your personal information?')) ?></h4>
                                <button class="shark-up toggle-shark"></button>
                            </div>
                            <div data-role="content" class="panel-collapse collapse in">
                                <div class="panel-body">
                                     <p><?= $block->escapeHtml(__('SharkNinja are responsible for determining “why” and “how” your personal information is collected. To be able to deliver our services we also determine which approved organisations we share your personal information with.  All these organisations are bound by an obligation to implement appropriate security measures and have specific contractual terms on “how” and “when” they are allowed to use your personal information on our behalf.')) ?></p>
                                      <br>
                                    <p><?= $block->escapeHtml(__('SharkNinja Europe Ltd and SharkNinja Operating LLC operate as joint data controllers.')) ?></p>
                                      <br>
                                   <p><?= $block->escapeHtml(__('You can contact us by whatever method is best for you, including by email and post.')) ?></p>
                                       <ul>
                                             <li><?= $block->escapeHtml(__('Our UK postal address: 3150 Century Way, Thorpe Park, Leeds, West Yorkshire, LS15 8ZB')) ?></li>
                                             <li><?= $block->escapeHtml(__('Our email address:')) ?> <strong><?= $block->escapeHtml(__(' privacy@sharkninja.com')) ?> </strong></li>
                                             <li><?= $block->escapeHtml(__('To submit a request to exercise your rights please click ')) ?><strong><a href="<?= $block->getUrl('contact') ?>"><?= $block->escapeHtml(__('here')) ?></a> </strong></li>
                                        </ul>  
                                    <p><?= $block->escapeHtml(__('If you require a copy of this notice in print, or would like us to share over the phone, please contact us -')) ?> <strong><?= $block->escapeHtml(__(' privacy@sharkninja.com')) ?> </strong><?= $block->escapeHtml(__(' or call ')) ?><strong><?= $block->escapeHtml(__('0800 862 0453.')) ?> </strong></p>
                       
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                            <div class="panel-heading" data-role="trigger">
                                <h4 class="panel-title"><?= $block->escapeHtml(__('What personal information do we collect and why?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                            <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">    
                            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('Children')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('Sharing and transferring personal information')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                                     <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('How long do we keep your personal information?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                                     <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
                                <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
                            </div>
                            </div>
                        </div>
                        <div class="panel" data-role="collapsible">
                         <div class="panel-heading" data-role="trigger">
                                 <h4 class="panel-title"><?= $block->escapeHtml(__('How do we protect your personal information?')) ?></h4>
                                <button class="shark-down toggle-shark"></button>
                            </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('International Transfer of Personal Information')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Your Data Protection Rights')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Right to lodge a complaint with a data protection supervisory.')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('How do you update your preferences or opt-out of marketing communications?')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
    </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Contact Us')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
    <div class="panel" data-role="collapsible">
     <div class="panel-heading" data-role="trigger">
             <h4 class="panel-title"><?= $block->escapeHtml(__('Changes to the Privacy Notice')) ?></h4>
            <button class="shark-down toggle-shark"></button>
        </div>
                                 <div data-role="content" class="panel-collapse collapse in">
                            <div class="panel-body">
            <p>To clean your Shark vacuum, follow these steps: [Cleaning Steps].</p>
        </div>
        </div>
        </div>
   

                    </div>
                </div>
            </div>
      

        <!-- Side panel for 'card-difficulty', occupying 30% of the width on the right -->
        <div class="col-md-4">
            <div class="card-difficulty">
                <div class="card-title">
                    <img src="<?= $block->getViewFileUrl('images/icons/question-icon.png') ?>" alt="package icon" class="img-fluid mb-2" style="max-width: 50px;">
                    <h6><?= $block->escapeHtml(__('Having difficulties?')) ?></h6>
                </div>
                    <p class="card-body"><?= $block->escapeHtml(__('If you have any problems or need help, please contact our Customer Service.')) ?></p>
                    <button class="btn-primary" href="<?= $block->getUrl('contact') ?>"><?= $block->escapeHtml(__('Go to support centre')) ?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
    var toggleButtons = document.querySelectorAll('.toggle-shark');
    toggleButtons.forEach(function(button) {
        button.addEventListener('click', function() {
            if (this.classList.contains('shark-up')) {
                this.classList.remove('shark-up');
                this.classList.add('shark-down');
            } else {
                this.classList.remove('shark-down');
                this.classList.add('shark-up');
            }
        });
    });
});
</script>
