<section class="product-hero-section">
    <div class="product-hero-section__image" style="background-image: url('<?php echo $block->getViewFileUrl('images/product-hero.png'); ?>');"></div>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-6">
                <div class="product-hero-section__inner">
                    <h3 class="text-xl text-bold">Deep cleaning, without the cord</h3>
                    <h3 class="text-2xl text-bold product-hero-section__title">We’ve got cordless covered</h3>
                    <p class="text-medium text-md text-line-height-24">Experience the power and freedom of Shark’s cordless vacuum cleaners. From flexible cordless stick vacuum cleaners to versatile cordless uprights, enjoy cord-free cleaning with a range of run-times to choose from.</p>
                    <a href="#" class="btn btn-black btn-sm">Shop all</a>
                </div>
            </div>
        </div>
    </div>
</section>