<section class="product-cards">
    <div class="container">
        <h2 class="text-bold text-3xl centre-title">Cordless vacumms</h2>
        <div class="row">
            <div class="col-md-4">
                <div class="product-card">
                    <img src="<?php echo $block->getViewFileUrl('images/product-landing/image(28).png'); ?>" class="product-card__image" alt="Shark Matrix™">
                    <div class="product-card__body">
                        <h3 class="text-bold text-xl">Anti Hair Wrap</h3>
                        <p class="text-md">Shark’s signature Anti Hair Wrap Technology.</p>
                        <a href="#" class="btn btn-black btn-sm">Shop Anti Hair Wrap</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="product-card">
                    <img src="<?php echo $block->getViewFileUrl('images/product-landing/image(29).png'); ?>" class="product-card__image" alt="Shark SmoothStyle™">
                    <div class="product-card__body">
                        <h3 class="text-bold text-xl">Shark Stratos</h3>
                        <p class="text-md">Discover a revolutionary cordless vacuum cleaner.</p>
                        <a href="#" class="btn btn-black btn-sm">Shop Shark Stratos</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="product-card">
                    <img src="<?php echo $block->getViewFileUrl('images/product-landing/image(30).png'); ?>" class="product-card__image" alt="Shark FlexBreeze™">
                    <div class="product-card__body">
                        <h3 class="text-bold text-xl">Shark Detect Pro</h3>
                        <p class="text-md">Shark’s most intelligent vacuum cleaner range.</p>
                        <a href="#" class="btn btn-black btn-sm">Shop Detect Pro</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>