<section class="products-slider background-gray-50">
    <div class="container">
        <h3 class="products-slider__title">Discover our Shark Stratos Cordless Range</h3>
        <div class="slick-in">
            <div id="product-slick-slider-2" data-mage-init='{"slick": {
            "infinite": true,
            "dots":true,
            "slidesToShow": 5,
            "slidesToScroll": 1,
            "responsive": [
    {
        "breakpoint": 0,
        "settings": {
            "slidesToShow": 1
        }
    },
    {
        "breakpoint": 481,
        "settings": {
            "slidesToShow": 1
        }
    },
    {
        "breakpoint": 768,
        "settings": {
            "slidesToShow": 2
        }
    },
    {
        "breakpoint": 992,
        "settings": {
            "slidesToShow": 2
        }
    },
    {
        "breakpoint": 1200,
        "settings": {
            "slidesToShow": 3
        }
    },
    {
        "breakpoint": 1441,
        "settings": {
            "slidesToShow": 4
        }
    },
    {
        "breakpoint": 1681,
        "settings": {
            "slidesToShow": 5
        }
    }
]

        }}'>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(22).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(23).png') ?>" alt="Shark FlexStyle® 5-in-1 Air Styler & Hair Dryer with Storage Case - Black/Rose Gold " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark FlexStyle® 5-in-1 Air Styler & Hair Dryer with Storage Case - Black/Rose Gold ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(23).png') ?>" alt="Shark CarpetXpert Deep Clean Pro Formula for Shark Upright & Portable Carpet cleaners " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark CarpetXpert Deep Clean Pro Formula for Shark Upright & Portable Carpet cleaners ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(24).png') ?>" alt="Shark Stratos Anti Hair Wrap Plus Pet Pro Cordless Vacuum (Double Battery)" class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Stratos Anti Hair Wrap Plus Pet Pro Cordless Vacuum (Double Battery)')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(25).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner  " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner  ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(24).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>


                <div class="item">
                    <div class="inner-slide">
                        <div class="product-card">
                            <img src="<?= $block->getViewFileUrl('images/product-slider/image(22).png') ?>" alt="Shark Detect Pro Cordless Vacuum Cleaner " class="img-fluid product-card__image" />
                            <div class="product-card__inner">
                                <div class="product-card__title">
                                    <h4 class="text-semi-bold text-sm"><?= $block->escapeHtml(__('Shark Detect Pro Cordless Vacuum Cleaner ')) ?></h4>
                                </div>
                                <div class="product-card__rating">
                                    <img src="<?= $block->getViewFileUrl('images/icons/5-stars.png') ?>" alt="5 Gold Stars" class="img-fluid five-stars" /><span class="text-bold text-lg">4.4
                                        <a href="#">(233)</a>
                                    </span>
                                </div>
                                <div class="product-card__price">
                                    <span class="text-xl text-bold">
                                        د.إ1635.85
                                    </span>
                                </div>
                                <div class="product-card__paypal"></div>
                                <a href="#" class="btn btn-black product-card__btn btn-sm">Add to cart</a>
                                <a href="#" class="product-card__details">See product details</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>